services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: admin123
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 3000
